# Generated by Django 5.2.10 on 2026-01-22 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sri', '0002_negara_provinsi_kabupaten'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendaftar',
            name='kabupaten',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sri.kabupaten'),
        ),
        migrations.AddField(
            model_name='pendaftar',
            name='negara',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sri.negara'),
        ),
        migrations.AddField(
            model_name='pendaftar',
            name='provinsi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sri.provinsi'),
        ),
    ]
