# Generated by Django 5.2.10 on 2026-01-22 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sri', '0003_pendaftar_kabupaten_pendaftar_negara_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='pendaftar',
            name='desa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sri.desa'),
        ),
        migrations.CreateModel(
            name='Kecamatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('kabupaten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sri.kabupaten')),
            ],
        ),
        migrations.AddField(
            model_name='desa',
            name='kecamatan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sri.kecamatan'),
        ),
        migrations.AddField(
            model_name='pendaftar',
            name='kecamatan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sri.kecamatan'),
        ),
    ]
